version: '3.8'

services:
  rv-lighting-control:
    build: .
    container_name: newmar_lighting
    ports:
      - "3060:3000"  # Web UI port
    volumes:
      - ./config:/app/config  # Mount config directory
      - ./data:/app/data      # Mount data directory for scenes/schedules
    environment:
      - NODE_ENV=production
      - CONFIG_FILE=/app/config/settings.json
    restart: unless-stopped
    networks:
      - rv-network

networks:
  rv-network:
    driver: bridge