version: '3.8'

services:
  rv-lighting-control:
    build: .
    ports:
      - "3000:3000"  # Web UI port
    volumes:
      - ./config:/app/config  # Mount config directory
      - ./data:/app/data      # Mount data directory for scenes/schedules
    environment:
      - NODE_ENV=production
      - CONFIG_FILE=/app/config/settings.json
    restart: unless-stopped
    networks:
      - rv-network

  # Optional: Add a simple file manager for config editing
  config-editor:
    image: filebrowser/filebrowser
    ports:
      - "3001:80"
    volumes:
      - ./config:/srv/config
      - ./data:/srv/data
    environment:
      - FB_BASEURL=/files
    restart: unless-stopped
    networks:
      - rv-network

networks:
  rv-network:
    driver: bridge

volumes:
  config:
  data: